Add froglight and shroomlight recipes from ATM9
AllTheMods/All-the-mods-9-Sky pull request #628
Opened 2024-07-29 11:41 UTC by tac-owo

I added these recipes to ATM9, and was asked to open a PR to add them to ATM9TTS, so here it is! Does need to be tested, though, as I don't play ATM9TTS. Should still work, it's the same file basically, but I can't be 100% sure.

2024-09-01 22:18 UTC, MaxwellRU commented
it will work only if you change  `allthemods.shaped(` to `event.shaped(` and `.id('allthemods:minecraft/` to `.id('kubejs:minecraft/`

2024-09-11 14:22 UTC, MaxwellRU requested changes
it will work only if you change  `allthemods.shaped(` to `event.shaped(`

2024-09-11 14:25 UTC, MaxwellRU commented on kubejs/server_scripts/mods/mysticalagriculture/crafting.js
> +
```js
// add recipe for warped wart block
  event.shaped('8x minecraft:warped_wart_block', [' A ', 'A  ', 'AAA'], {
    A: 'mysticalagriculture:nether_essence'
  }).id('kubejs:minecraft/warped_wart_block')
```

2024-09-11 14:27 UTC, MaxwellRU commented on kubejs/server_scripts/mods/mysticalagriculture/crafting.js
> +
```js
//add recipes for froglights
  event.shaped('8x minecraft:ochre_froglight', ['NDG', 'GDN', 'NDG'], {
    N: 'mysticalagriculture:nature_essence',
    D: 'mysticalagriculture:dye_essence',
    G: 'mysticalagriculture:glowstone_essence'
  }).id('kubejs:minecraft/ochre_froglight')
```

2024-12-09 22:03 UTC, MaxwellRU approved these changes
they are good

2025-05-20 14:02 UTC, Satherov commented
Added with 5168385

2025-05-20 14:02 UTC, closed without merging